# Generated by Django 3.0.5 on 2020-09-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mazaoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmers',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
