# Generated by Django 3.0.5 on 2020-09-11 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mazaoapp', '0002_auto_20200911_2020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Farmers',
            new_name='Farmer',
        ),
    ]
