# Generated by Django 3.0.5 on 2020-09-15 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mazaoapp', '0005_auto_20200915_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='registered',
            new_name='date',
        ),
    ]
