# Generated by Django 3.0.5 on 2020-09-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mazaoapp', '0007_remove_farmer_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
